// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {

	    int n = Integer.parseInt(args[0]);
		int countBelow = 0;
		int countAbove = 0;

		// generates random numbers n times and checks if they are lesser than or
		// greater/equal to 0.5 . If so, we add 1 to the counters accordingly
		while (n > 0)
		{
			double num = Math.random();
			n--;
			if (num>0.5) {
				countAbove++;
			}
			else {
				countBelow++;
			}
		}

		//caclulate the ratio of the two integers by dividing one by the other
		double ratio = countAbove / (double)countBelow;

		System.out.println("> 0.5:  " + countAbove + " times");
		System.out.println("<= 0.5: " + countBelow + " times");
		System.out.println("Ratio:  " + ratio);
	}
}
